services:
  pingservice:
    image: pingservice
    user: root
    build:
      context: .
      dockerfile: PingService/Dockerfile
    ports:
      - "5002:80"
  webapiconsumingbasichttp:
    image: webapiconsumingbasichttp
    user: root
    depends_on:
      - pingservice
    build:
      context: .
      dockerfile: WebApiConsumingBasicHttp/Dockerfile
    ports:
      - "5003:80"
